---
title: "`r paste('Wellness Report - ', params$patient, sep = '')`"
subtitle: "`r params$therapist`"
format:
  html:
    embed-resources: true
    theme: journal
editor: visual
output:
  html_document:
  pdf_document: 
    keep_tex: true
params:
  data: NA
  patient: NA
  therapist: NA
  roll_window: NA
  current_dir: getwd()
execute:
  echo: false
  warnings: false
  cache: false
runtime: shiny
---

```{r}
#| echo:    FALSE
#| message: FALSE
#| warning: FALSE

library(kableExtra)
library(shiny)
library(tidyverse)
library(zoo)
library(ggplot2)
library(knitr)
library(grid)
library(readxl)

rolling_mean <- function(x) {
  rollmean(x, k = 3, fill = NA, align = 'right')
}

scale_func <- function(x) {
  sprintf("%.1f", x)
}

perc_change <- function(x) {
  round((tail(x, 1) - head(x, 1)) / head(x, 1) * 100, digits = 1)
}

opts_knit$set(
  root.dir = getwd()
)



# test_path <- "C:/Users/Caitie Mayo/OneDrive - Architech Sports and Physical Therapy/Performance Analyst/Wellness Questionnaire/Physical Therapy Wellness Questionnaire/pt_wellness_questionnaire.xlsx"
# params$data <- read_excel(path = test_path, sheet = 'Form1')
# params$patients <- unique(data$`What is your name?`)
# params$therapist <- unique(data$`Who is your Physical Therapist?`)

```

```{r}
#| echo:    FALSE
#| message: FALSE
#| warning: FALSE

# # Create Patient Select Dropdown
# selectInput(
#   inputId  = 'patientSelect',
#   label    = 'Select patient to view',
#   choices  = patients,
#   selected = head(patients, 1)
# )
data <- params$data
data <- data[data$Name == params$patient, ]

```

:::::: {.cols style='display: flex;'}

<div class = "col-md-4">
### SANE

`r perc_change(data$SANE)`%
</div>

<div class = "col-md-4">
### Performance

`r perc_change(data$Performance)`%
</div>

<div class = "col-md-4">
### Wellness

`r perc_change(data$Wellness)`%
</div>

::::::

:::::: {.cols style='display: flex;'}

<div class = "col-md-4">
### Sleep

`r perc_change(data$Sleep)`%
</div>

<div class = "col-md-4">
### Frequency

`r perc_change(data$Frequency)`%
</div>

<div class = "col-md-4">
### Severity

`r perc_change(data$Severity)`%
</div>

::::::

```{r}
#| echo:    FALSE
#| message: FALSE
#| warning: FALSE
#| output: asis

plot <- data %>%
  pivot_longer(
    cols = !c(Date, Name, Therapist),
    names_to = "Question",
    values_to = "Response",
    values_drop_na = TRUE
  ) %>%
  group_by(Question) %>%
  mutate(roll_mean = rollmean(Response, 
                              k = as.integer(params$roll_window),
                              fill = NA, align = 'right')) %>%
  mutate(Question = factor(Question, 
                           levels = c('SANE', 'Performance', 'Wellness', 'Sleep', 'Frequency', 'Severity'))) %>%
  ggplot(mapping = aes(x = Date, y = Response)) +
  geom_area(aes(color = Question, fill = Question, alpha = 0.5)) +
  geom_point()

if (length(data$Name) > 1) {
  plot <- plot + 
    geom_line(aes(y = roll_mean))
}

plot <- plot +
  facet_wrap(~Question, nrow = 2, scales = 'free') +
  theme_gray() +
  theme(legend.position = 'none',
        panel.spacing = unit(2, 'lines'),
        axis.title.x = element_blank()) +
  scale_y_continuous(labels = scale_func)

plot
```
